import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { deleteReportApi } from '../../api/reportApi';
import ScreenHeader from '../../components/ScreenHeader';
import { COLORS, FONTS, RADIUS, SHADOW } from '../../theme';

const formatLabel = (value) =>
  String(value || '')
    .replace(/_/g, ' ')
    .replace(/([A-Z])/g, ' $1')
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());

const DataValue = ({ label, value }) => (
  <View style={styles.metricItem}>
    <Text style={styles.metricLabel}>{formatLabel(label)}</Text>
    {Array.isArray(value) ? (
      value.length === 0 ? (
        <Text style={styles.metricValue}>None</Text>
      ) : (
        value.map((item, index) => (
          <View key={`${label}-${index}`} style={styles.inlineRowCard}>
            {Object.entries(item).map(([key, nestedValue]) => (
              <Text key={key} style={styles.inlineRowText}>
                {formatLabel(key)}: {String(nestedValue ?? 'N/A')}
              </Text>
            ))}
          </View>
        ))
      )
    ) : (
      <Text style={styles.metricValue}>{String(value ?? 'N/A')}</Text>
    )}
  </View>
);

const ReportDetailsScreen = ({ route, navigation }) => {
  const { report } = route.params || {};
  const data = report?.data;
  const rows = Array.isArray(data) ? data : null;
  const metrics = !Array.isArray(data) && data && typeof data === 'object' ? Object.entries(data) : [];

  const handleDelete = () => {
    Alert.alert(
      'Delete Report',
      'Delete this generated report? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteReportApi(report._id);
              Alert.alert('Deleted', 'Report deleted successfully.');
              navigation.goBack();
            } catch (error) {
              Alert.alert('Delete Failed', error.response?.data?.message || 'Unable to delete report.');
            }
          },
        },
      ]
    );
  };

  return (
    <View style={styles.root}>
      <ScreenHeader
        title={report?.title || 'Report Details'}
        subtitle={report?.reportType?.replace('_', ' ') || 'Generated report'}
        onBack={() => navigation.goBack()}
      />
      <ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.summaryCard}>
          <Text style={styles.title}>{report?.title || 'Report'}</Text>
          <Text style={styles.meta}>Generated by {report?.generatedBy?.name || 'Admin'}</Text>
          {report?.createdAt ? (
            <Text style={styles.meta}>{new Date(report.createdAt).toLocaleString()}</Text>
          ) : null}
        </View>

        {rows ? (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Report Data</Text>
            {rows.length === 0 ? (
              <Text style={styles.emptyText}>No rows found.</Text>
            ) : (
              rows.map((row, index) => (
                <View key={`${row.doctorId || index}`} style={styles.rowCard}>
                  {Object.entries(row).map(([key, value]) => (
                    <DataValue key={key} label={key} value={value} />
                  ))}
                </View>
              ))
            )}
          </View>
        ) : (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Report Data</Text>
            {metrics.map(([key, value]) => (
              <DataValue key={key} label={key} value={value} />
            ))}
          </View>
        )}

        <View style={styles.dangerCard}>
          <Text style={styles.dangerTitle}>Danger Zone</Text>
          <Text style={styles.dangerText}>Remove this generated report from admin records.</Text>
          <TouchableOpacity style={styles.deleteBtn} onPress={handleDelete} activeOpacity={0.85}>
            <Text style={styles.deleteText}>Delete Report</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bgPage },
  scroll: { flex: 1 },
  content: { padding: 16, paddingTop: 20, paddingBottom: 40 },
  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 14,
    ...SHADOW.card,
  },
  title: { fontSize: 18, fontWeight: FONTS.bold, color: COLORS.navyDeep },
  meta: { fontSize: 12, color: COLORS.textMuted, marginTop: 4 },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 14,
    ...SHADOW.card,
  },
  cardTitle: { fontSize: 13, fontWeight: FONTS.bold, color: COLORS.navyDeep, marginBottom: 12 },
  metricItem: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingVertical: 10,
  },
  metricLabel: { fontSize: 11, color: COLORS.textMuted, fontWeight: FONTS.bold, letterSpacing: 0.6 },
  metricValue: { fontSize: 15, color: COLORS.navyDeep, fontWeight: FONTS.semibold, marginTop: 3 },
  rowCard: {
    backgroundColor: COLORS.bgMuted,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  inlineRowCard: {
    backgroundColor: COLORS.bgMuted,
    borderRadius: RADIUS.md,
    padding: 10,
    marginTop: 8,
  },
  inlineRowText: {
    fontSize: 12,
    color: COLORS.navyDeep,
    lineHeight: 18,
  },
  emptyText: { fontSize: 13, color: COLORS.textMuted },
  dangerCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.dangerBg,
    ...SHADOW.card,
  },
  dangerTitle: { fontSize: 14, fontWeight: FONTS.bold, color: COLORS.danger, marginBottom: 4 },
  dangerText: { fontSize: 12, color: COLORS.textMuted, marginBottom: 12 },
  deleteBtn: {
    backgroundColor: COLORS.danger,
    borderRadius: RADIUS.md,
    paddingVertical: 12,
    alignItems: 'center',
  },
  deleteText: { color: COLORS.white, fontWeight: FONTS.bold, fontSize: 13 },
});

export default ReportDetailsScreen;
